export const BusinessProgramCategories = {
  WARRANTY: "WARRANTY",
  AMC: "AMC",
  GOODWILL: "GOODWILL",
  FSB: "FSB",
  CAMPAIGN: "CAMPAIGN",
  INSURANCE: "INSURANCE",
  FLEET_CONTRACT: "FLEET_CONTRACT",
  INTERNAL_REPAIR: "INTERNAL_REPAIR"
} as const;

export const FinancialStatus = {
  PENDING: "PENDING",
  APPROVED: "APPROVED",
  PARTIALLY_APPROVED: "PARTIALLY_APPROVED",
  REJECTED: "REJECTED",
  SETTLED: "SETTLED"
} as const;
