export const GoodwillCategories = {
  FULL_GOODWILL: "FULL_GOODWILL",
  PARTIAL_GOODWILL: "PARTIAL_GOODWILL",
  LABOUR_ONLY: "LABOUR_ONLY",
  PARTS_ONLY: "PARTS_ONLY",
  COMMERCIAL_GOODWILL: "COMMERCIAL_GOODWILL",
  CUSTOMER_RETENTION: "CUSTOMER_RETENTION",
  REPEAT_FAILURE: "REPEAT_FAILURE",
  FLEET_SUPPORT: "FLEET_SUPPORT",
  CAMPAIGN_SUPPORT: "CAMPAIGN_SUPPORT",
  OEM_SPECIAL_APPROVAL: "OEM_SPECIAL_APPROVAL"
} as const;

export const GoodwillStatus = {
  DRAFT: "DRAFT",
  EVALUATING: "EVALUATING",
  PENDING_APPROVAL: "PENDING_APPROVAL",
  APPROVED: "APPROVED",
  REJECTED: "REJECTED",
  MANUAL_REVIEW: "MANUAL_REVIEW",
  CLOSED: "CLOSED"
} as const;

export const GoodwillEligibilityStatus = {
  ELIGIBLE: "ELIGIBLE",
  CONDITIONALLY_ELIGIBLE: "CONDITIONALLY_ELIGIBLE",
  REJECTED: "REJECTED",
  MANUAL_REVIEW: "MANUAL_REVIEW"
} as const;

export const RiskLevels = {
  LOW: "LOW",
  MEDIUM: "MEDIUM",
  HIGH: "HIGH",
  POTENTIAL_ABUSE: "POTENTIAL_ABUSE"
} as const;
