export const GoodwillReasonCodes = [
  "CUSTOMER_RETENTION",
  "DEALER_ERROR",
  "OEM_DEFECT",
  "MARKET_COMPETITION",
  "TRANSIT_DAMAGE",
  "REPEAT_FAILURE",
  "FLEET_SUPPORT",
  "CAMPAIGN_ADJUSTMENT",
  "SPECIAL_APPROVAL"
] as const;
