/**
 * DWIP Enterprise WOS - VOS System Constants
 * Task 1.2 VOS Service Layer
 */

export const VOS_CONSTANTS = {
  DEFAULT_FINANCIAL_YEAR: '2026',
  DEFAULT_DATA_CLASSIFICATION: 'INTERNAL',
  DEFAULT_CURRENT_STATE: 'GATE_IN',
  DEFAULT_STATE_CODE: 'STATE_GATE_IN',
  DEFAULT_OPERATIONAL_STATUS: 'ACTIVE',
  MIN_RISK_SCORE: 0,
  MAX_RISK_SCORE: 100,
  SYSTEM_ACTOR: 'SYSTEM_VOS_SERVICE'
};
