export const DispatchRules = {
  MAX_RADIUS_KM_FOR_QRT: 50,
  MAX_RADIUS_KM_FOR_TOW: 100,
  PREFER_NEAREST_WORKSHOP: true
};

export const SlaRules = {
  MAX_RESPONSE_TIME_MINS: 15,
  MAX_ETA_MINS_URBAN: 60,
  MAX_ETA_MINS_HIGHWAY: 120,
  MAX_RESOLUTION_TIME_HOURS: 24
};

export const RecoveryRules = {
  AUTO_ASSIGN_TOW_ON_ACCIDENT: true,
  AUTO_ASSIGN_TOW_ON_ENGINE_FAILURE: true,
  TOW_REQUIRED_IF_REPAIR_FAILS_ONSITE: true
};
