export const BreakdownSeverityMatrix = {
  CRITICAL: ["ACCIDENT", "ENGINE_FIRE", "BRAKE_FAILURE"],
  MAJOR: ["ENGINE_STALL", "CLUTCH_FAILURE", "TRANSMISSION_ISSUE"],
  MINOR: ["FLAT_TIRE", "OUT_OF_FUEL", "LOCKOUT", "BATTERY_JUMP_START"]
};
