export const InsurancePolicyStatus = {
  ACTIVE: "ACTIVE",
  EXPIRED: "EXPIRED",
  SUSPENDED: "SUSPENDED",
  CANCELLED: "CANCELLED",
  PENDING_RENEWAL: "PENDING_RENEWAL"
} as const;

export const InsuranceClaimStatus = {
  DRAFT: "DRAFT",
  SUBMITTED: "SUBMITTED",
  VALIDATED: "VALIDATED",
  APPROVED: "APPROVED",
  REJECTED: "REJECTED",
  SETTLED: "SETTLED",
  CLOSED: "CLOSED"
} as const;

export const CoverageStatus = {
  COVERED: "COVERED",
  PARTIALLY_COVERED: "PARTIALLY_COVERED",
  NOT_COVERED: "NOT_COVERED",
  EXPIRED: "EXPIRED",
  EXCLUDED: "EXCLUDED",
  MANUAL_REVIEW: "MANUAL_REVIEW"
} as const;

export const FleetEligibilityStatus = {
  ELIGIBLE: "ELIGIBLE",
  EXPIRED: "EXPIRED",
  EXCEEDED_LIMITS: "EXCEEDED_LIMITS",
  INACTIVE: "INACTIVE",
  SUSPENDED: "SUSPENDED",
  MANUAL_REVIEW: "MANUAL_REVIEW"
} as const;
