export const InsuranceRenewalRules = {
  RENEWAL_WINDOW_DAYS_BEFORE_EXPIRY: 30,
  GRACE_PERIOD_DAYS_AFTER_EXPIRY: 15,
  MAX_NO_CLAIM_BONUS_PERCENT: 50,
  NO_CLAIM_BONUS_YEARLY_INCREMENT: 10
};

export const FleetRenewalRules = {
  RENEWAL_WINDOW_DAYS: 60,
  AUTO_RENEW_ELIGIBLE: true
};
