export const FsbCampaignStatus = {
  DRAFT: "DRAFT",
  ACTIVE: "ACTIVE",
  SUSPENDED: "SUSPENDED",
  CLOSED: "CLOSED",
  CANCELLED: "CANCELLED"
} as const;

export const FsbVehicleStatus = {
  ELIGIBLE: "ELIGIBLE",
  ALREADY_COMPLETED: "ALREADY_COMPLETED",
  EXPIRED: "EXPIRED",
  REJECTED: "REJECTED",
  PENDING: "PENDING",
  DUPLICATE: "DUPLICATE",
  BLOCKED: "BLOCKED",
  MANUAL_REVIEW: "MANUAL_REVIEW"
} as const;

export const FsbClaimStatus = {
  PENDING: "PENDING",
  SUBMITTED: "SUBMITTED",
  VALIDATED: "VALIDATED",
  APPROVED: "APPROVED",
  REJECTED: "REJECTED",
  SETTLED: "SETTLED"
} as const;
