import React from "react";
import { CheckCircle2, Clock, Wrench, ShieldCheck, DollarSign, FileText, Truck, AlertTriangle, UserCheck } from "lucide-react";

export interface TimelineEvent {
  id: string;
  stage: string;
  title: string;
  description: string;
  timestamp: string;
  actor?: string;
  status: "completed" | "current" | "pending";
  icon?: string;
}

interface EventServiceTimelineProps {
  events?: TimelineEvent[];
  currentStage?: string;
}

export const EventServiceTimeline: React.FC<EventServiceTimelineProps> = ({
  events,
  currentStage = "WIP_START"
}) => {
  // Default comprehensive event lifecycle if none provided
  const defaultEvents: TimelineEvent[] = [
    {
      id: "evt-1",
      stage: "GATE_IN",
      title: "Gate Security Entry & ANPR Scan",
      description: "Vehicle registered at Security Gate Inward. Odometer: 142,500 KM | Fuel: 75%.",
      timestamp: "Today, 09:15 AM",
      actor: "Security Gate Officer",
      status: "completed"
    },
    {
      id: "evt-2",
      stage: "INTAKE_PENDING",
      title: "Reception Vehicle Intake & Digital Inspection",
      description: "Customer complaint registered & 360° vehicle photo deck captured.",
      timestamp: "Today, 09:28 AM",
      actor: "Service Receptionist",
      status: "completed"
    },
    {
      id: "evt-3",
      stage: "ESTIMATE_PENDING",
      title: "Diagnostic Inspection & Estimate Generation",
      description: "Labour & Spares estimate generated by Service Advisor. Sent for customer 1-click approval.",
      timestamp: "Today, 09:45 AM",
      actor: "Service Advisor (Sunil Kumar)",
      status: "completed"
    },
    {
      id: "evt-4",
      stage: "ESTIMATE_APPROVED",
      title: "Customer 1-Click Estimate Approval",
      description: "Estimate of ₹14,850 approved online via Customer Portal.",
      timestamp: "Today, 10:02 AM",
      actor: "Vehicle Owner (Approved Online)",
      status: "completed"
    },
    {
      id: "evt-5",
      stage: "PARTS_PENDING",
      title: "Spares Requisition & Store Release",
      description: "OEM Brake Pads & Engine Oil issued from main parts warehouse to Bay #4.",
      timestamp: "Today, 10:18 AM",
      actor: "Spares Store Manager",
      status: "completed"
    },
    {
      id: "evt-6",
      stage: "WIP_START",
      title: "Active Work-In-Progress (Bay #4)",
      description: "Technician assigned and replacement servicing in progress.",
      timestamp: "Today, 10:30 AM",
      actor: "Lead Tech: Khaja Moinuddin",
      status: currentStage === "WIP_START" ? "current" : "completed"
    },
    {
      id: "evt-7",
      stage: "QC_PENDING",
      title: "Quality Check & Road Test Inspection",
      description: "Comprehensive 24-point quality inspection and road test check.",
      timestamp: "Estimated 11:45 AM",
      actor: "QC Inspector",
      status: ["QC_PENDING", "FINAL_REVIEW", "COMPLETED"].includes(currentStage) ? "completed" : "pending"
    },
    {
      id: "evt-8",
      stage: "FINAL_REVIEW",
      title: "Tax Invoice Generation & Digital Settlement",
      description: "Final invoice generated with online UPI / Card payment settlement.",
      timestamp: "Estimated 12:15 PM",
      actor: "Cashier Desk",
      status: ["FINAL_REVIEW", "COMPLETED"].includes(currentStage) ? "completed" : "pending"
    },
    {
      id: "evt-9",
      stage: "GATE_OUT",
      title: "Gate Clearance & Vehicle Delivery",
      description: "Gate Pass issued for smooth vehicle clearance.",
      timestamp: "Estimated 12:30 PM",
      actor: "Gate Security Officer",
      status: currentStage === "COMPLETED" ? "completed" : "pending"
    }
  ];

  const timelineList = events && events.length > 0 ? events : defaultEvents;

  return (
    <div className="bg-white rounded-2xl p-5 border border-slate-200 shadow-sm space-y-4">
      <div className="flex items-center justify-between pb-3 border-b border-slate-100">
        <div>
          <h3 className="text-xs font-extrabold text-slate-800 uppercase tracking-wider flex items-center gap-2">
            <Clock className="w-4 h-4 text-indigo-600" />
            Event-Driven Service Lifecycle Timeline
          </h3>
          <p className="text-[10px] text-slate-500 font-medium">Real-time chronological activity log of your vehicle's workshop journey</p>
        </div>

        <span className="px-2.5 py-1 rounded-full bg-indigo-50 border border-indigo-200 text-indigo-700 text-[10px] font-extrabold uppercase">
          Live Tracking Active
        </span>
      </div>

      <div className="relative pl-6 space-y-6 before:absolute before:left-2.5 before:top-2.5 before:bottom-2.5 before:w-0.5 before:bg-slate-200">
        {timelineList.map((evt, idx) => {
          const isCompleted = evt.status === "completed";
          const isCurrent = evt.status === "current";

          return (
            <div key={evt.id || idx} className="relative group">
              {/* Timeline Marker Circle */}
              <div 
                className={`absolute -left-6 top-0.5 w-5 h-5 rounded-full flex items-center justify-center text-[10px] font-bold transition-all ${
                  isCompleted 
                    ? "bg-emerald-600 text-white shadow-md ring-4 ring-emerald-100" 
                    : isCurrent 
                    ? "bg-indigo-600 text-white shadow-lg ring-4 ring-indigo-100 animate-pulse" 
                    : "bg-slate-200 text-slate-500 border border-slate-300"
                }`}
              >
                {isCompleted ? "✓" : idx + 1}
              </div>

              {/* Event Card Content */}
              <div 
                className={`p-3.5 rounded-xl border transition-all ${
                  isCurrent 
                    ? "bg-indigo-50/70 border-indigo-200 shadow-sm" 
                    : isCompleted 
                    ? "bg-slate-50/80 border-slate-200" 
                    : "bg-white border-slate-150 opacity-60"
                }`}
              >
                <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-1 mb-1">
                  <h4 className={`text-xs font-bold ${isCurrent ? "text-indigo-950" : "text-slate-900"}`}>
                    {evt.title}
                  </h4>
                  <span className="text-[10px] font-mono font-semibold text-slate-500">
                    {evt.timestamp}
                  </span>
                </div>

                <p className="text-[11px] text-slate-600 leading-relaxed font-normal">
                  {evt.description}
                </p>

                {evt.actor && (
                  <div className="mt-2 pt-2 border-t border-slate-200/50 flex items-center gap-1.5 text-[10px] font-medium text-slate-500">
                    <UserCheck className="w-3 h-3 text-slate-400" />
                    <span>Actor: <strong className="text-slate-700">{evt.actor}</strong></span>
                  </div>
                )}
              </div>
            </div>
          );
        })}
      </div>
    </div>
  );
};
