/**
 * DWIP Enterprise WOS - WorkflowCapability
 * Task 2.2 Standardized Operational Capability Definitions (12 Capabilities)
 */

export enum WorkflowCapability {
  FAST_TRACK = 'FAST_TRACK',
  SKIP_ESTIMATE = 'SKIP_ESTIMATE',
  OEM_PRE_APPROVAL = 'OEM_PRE_APPROVAL',
  GM_CONCESSION_APPROVAL = 'GM_CONCESSION_APPROVAL',
  PREPAID_CONTRACT = 'PREPAID_CONTRACT',
  INTERNAL_DIRECT_WORK = 'INTERNAL_DIRECT_WORK',
  QRT_DISPATCH = 'QRT_DISPATCH',
  RECALL_CAMPAIGN_WORK = 'RECALL_CAMPAIGN_WORK',
  DIRECT_BAY_ASSIGNMENT = 'DIRECT_BAY_ASSIGNMENT',
  CUSTOMER_APPROVAL_REQUIRED = 'CUSTOMER_APPROVAL_REQUIRED',
  ALLOW_PARTIAL_DELIVERY = 'ALLOW_PARTIAL_DELIVERY',
  MULTI_STAGE_APPROVAL = 'MULTI_STAGE_APPROVAL'
}
